export const SET_STAR_MASS = "SET_STAR_MASS";
export const SET_STAR_NAME = "SET_STAR_NAME";
export const SET_STAR_TYPE = "SET_STAR_TYPE";
export const SET_STAR_SIZE = "SET_STAR_SIZE";
export const SET_STAR_TEMPERATURE = "SET_STAR_TEMPERATURE";
