export const ASSIGN_PLANET_TO_ORBIT = "ASSIGN_PLANET_TO_ORBIT";

export const UNASSIGN_PLANET_FROM_ORBIG = "UNASSIGN_PLANET_FROM_ORBIT";

export const ADD_STAR_TO_SYSTEM = "ADD_STAR_TO_SYSTEM";
export const ADD_PLANET_TO_SYSTEM = "ADD_PLANET_TO_SYSTEM";
