export const SET_PLANET_NAME = "SET_PLANET_NAME";
export const SET_PLANET_TYPE = "SET_PLANET_TYPE";
export const SET_PLANET_SIZE = "SET_PLANET_SIZE";
export const SET_PLANET_TEMPERATURE_ADJUSTMENT =
  "SET_PLANET_TEMPERATURE_ADJUSTMENT";
export const SET_PLANET_HUE_COLOR = "SET_PLANET_HUE_COLOR";

export const CLEAR_PLANET_FORM = "CLEAR_PLANET_FORM";
